[2022-07-19 06:51:19,236] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator.delete_data_from_table scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-19 06:51:19,269] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator.delete_data_from_table scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-19 06:51:19,269] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 06:51:19,269] {taskinstance.py:1244} INFO - Starting attempt 1 of 6
[2022-07-19 06:51:19,270] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 06:51:19,317] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2022-07-18 00:00:00+00:00
[2022-07-19 06:51:19,325] {standard_task_runner.py:52} INFO - Started process 658 to run task
[2022-07-19 06:51:19,343] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'delete_data_from_table', 'scheduled__2022-07-18T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/example_postgres.py', '--cfg-path', '/tmp/tmp2n04un3a', '--error-file', '/tmp/tmpyv6ep_n1']
[2022-07-19 06:51:19,344] {standard_task_runner.py:77} INFO - Job 56: Subtask delete_data_from_table
[2022-07-19 06:51:19,487] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_with_postgres_operator.delete_data_from_table scheduled__2022-07-18T00:00:00+00:00 [running]> on host 0741836b2d3b
[2022-07-19 06:51:19,658] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kimuksung2
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator
AIRFLOW_CTX_TASK_ID=delete_data_from_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-18T00:00:00+00:00
[2022-07-19 06:51:19,681] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: test, Login: ***, Password: ***, extra: {}
[2022-07-19 06:51:19,723] {dbapi.py:225} INFO - Running statement: 
            delete from dag_runs where dt = '2022-07-18' and dag_id = 'dag_with_postgres_operator';
        , parameters: None
[2022-07-19 06:51:19,744] {dbapi.py:233} INFO - Rows affected: 1
[2022-07-19 06:51:19,799] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator, task_id=delete_data_from_table, execution_date=20220718T000000, start_date=20220719T065119, end_date=20220719T065119
[2022-07-19 06:51:19,852] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-19 06:51:19,920] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-19 07:03:26,035] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator.delete_data_from_table scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-19 07:03:26,069] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator.delete_data_from_table scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-19 07:03:26,069] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 07:03:26,069] {taskinstance.py:1244} INFO - Starting attempt 1 of 6
[2022-07-19 07:03:26,069] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 07:03:26,087] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2022-07-18 00:00:00+00:00
[2022-07-19 07:03:26,091] {standard_task_runner.py:52} INFO - Started process 985 to run task
[2022-07-19 07:03:26,095] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'delete_data_from_table', 'scheduled__2022-07-18T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/example_postgres.py', '--cfg-path', '/tmp/tmpsvh1fxba', '--error-file', '/tmp/tmpvgi4_2t2']
[2022-07-19 07:03:26,095] {standard_task_runner.py:77} INFO - Job 64: Subtask delete_data_from_table
[2022-07-19 07:03:26,167] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_with_postgres_operator.delete_data_from_table scheduled__2022-07-18T00:00:00+00:00 [running]> on host 0741836b2d3b
[2022-07-19 07:03:26,237] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kimuksung2
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator
AIRFLOW_CTX_TASK_ID=delete_data_from_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-18T00:00:00+00:00
[2022-07-19 07:03:26,253] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: postgres, Port: 5432, Schema: test, Login: ***, Password: ***, extra: {}
[2022-07-19 07:03:26,258] {dbapi.py:225} INFO - Running statement: 
            delete from dag_runs where dt = '2022-07-18' and dag_id = 'dag_with_postgres_operator';
        , parameters: None
[2022-07-19 07:03:26,260] {dbapi.py:233} INFO - Rows affected: 0
[2022-07-19 07:03:26,277] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator, task_id=delete_data_from_table, execution_date=20220718T000000, start_date=20220719T070326, end_date=20220719T070326
[2022-07-19 07:03:26,306] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-19 07:03:26,358] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
