[2022-07-19 06:50:58,484] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator.create_postgres_table manual__2022-07-19T06:50:56.561772+00:00 [queued]>
[2022-07-19 06:50:58,504] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator.create_postgres_table manual__2022-07-19T06:50:56.561772+00:00 [queued]>
[2022-07-19 06:50:58,504] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 06:50:58,504] {taskinstance.py:1244} INFO - Starting attempt 1 of 6
[2022-07-19 06:50:58,504] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 06:50:58,528] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-07-19 06:50:56.561772+00:00
[2022-07-19 06:50:58,538] {standard_task_runner.py:52} INFO - Started process 642 to run task
[2022-07-19 06:50:58,544] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'create_postgres_table', 'manual__2022-07-19T06:50:56.561772+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/example_postgres.py', '--cfg-path', '/tmp/tmp173kpipa', '--error-file', '/tmp/tmpvy4jnriz']
[2022-07-19 06:50:58,545] {standard_task_runner.py:77} INFO - Job 52: Subtask create_postgres_table
[2022-07-19 06:50:58,683] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_with_postgres_operator.create_postgres_table manual__2022-07-19T06:50:56.561772+00:00 [running]> on host 0741836b2d3b
[2022-07-19 06:50:58,815] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kimuksung2
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T06:50:56.561772+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-19T06:50:56.561772+00:00
[2022-07-19 06:50:58,830] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: test, Login: ***, Password: ***, extra: {}
[2022-07-19 06:50:59,014] {dbapi.py:225} INFO - Running statement: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2022-07-19 06:50:59,035] {postgres.py:73} INFO - NOTICE:  relation "dag_runs" already exists, skipping

[2022-07-19 06:50:59,070] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator, task_id=create_postgres_table, execution_date=20220719T065056, start_date=20220719T065058, end_date=20220719T065059
[2022-07-19 06:50:59,228] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-19 06:51:06,901] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
